title: Wanxiang Qin's Homepage
page-top-title: Wanxiang Qin
top-section-bg-text: Computer Science
home-subtitle: Wanxiang Qin&ensp;|&ensp;覃万祥
copyright-text: '&copy; Wanxiang Qin 2023-2025. All Rights Reserved.'
